"""Connector credential encryption (docs/mycelic/INGESTION.md §10.1, decision I10).

Envelope encryption with AES-256-GCM (PyCA ``cryptography``; the standard library has no authenticated cipher and a
hand-built HMAC stream cipher is not acceptable):

    master key (MYCELIC_SECRET_KEY) --HKDF-SHA256, per tenant--> KEK --wraps--> per-connector DEK (random 32 bytes)
                                                                                  --encrypts--> credential JSON

* Both layers authenticate ``aad = 'mycelic/cred/v1|<tenant>|<holder>|<connector>'`` (the wrap adds ``|wrap``). :meth:`open`
  recomputes the AAD from the caller's ids, so a row copied to another holder or connector fails authentication, and any
  modified byte of the wrapped key or the ciphertext raises :class:`CredentialTampered`.
* Nonces are random 96-bit values, fresh for every seal and every :meth:`replace_credentials`.
* Deleting the ``connector_credentials`` row deletes the wrapped DEK: the credentials are crypto-shredded.
* Key rotation: :meth:`rewrap` unwraps the DEK with the old key id and wraps it with the active one; the ciphertext is
  unchanged. Previous master keys (``MYCELIC_SECRET_KEY_PREVIOUS``, comma-separated) are kept for unwrapping only.
* A master key that ``runtime.ensure_secret_key`` generated next to the databases is refused (a copy of the volume would
  carry both the ciphertext and the key) unless ``MYCELIC_ALLOW_LOCAL_KEK=1`` (development).

The import of ``cryptography`` is lazy, so connectors without credentials work without the package.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

from .contract import Credentials

FORMAT = b"v1"
NONCE_BYTES = 12


class VaultUnavailable(RuntimeError):
    """No acceptable master key (unset, or auto-generated next to the data without MYCELIC_ALLOW_LOCAL_KEK=1)."""


class CredentialTampered(RuntimeError):
    """Authentication failed: the row was modified, moved to another holder/connector, or the key is wrong."""


@dataclass(frozen=True)
class SealedCredentials:
    kid: str
    wrapped_dek: bytes
    ciphertext: bytes
    aad: str


def _aesgcm():
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError as exc:   # pragma: no cover - dependency is in requirements-mycelic.txt
        raise VaultUnavailable("the 'cryptography' package is required for connector credentials") from exc
    return AESGCM


def kid_for(master: bytes) -> str:
    """The key id stored next to every sealed credential. It is derived with scrypt, not a fast hash, so a copy of the
    database is not a cheap oracle for guessing a weak master key (a strong random key needs no such help)."""
    return "k" + hashlib.scrypt(master, salt=b"mycelic/kid/v1", n=2 ** 14, r=8, p=1, dklen=12).hex()


def legacy_kid_for(master: bytes) -> str:
    """Key ids written before the scrypt derivation, still accepted for unwrapping (and rewrapped on rotation)."""
    return "k" + hashlib.sha256(master).hexdigest()[:16]


def aad_for(tenant_id: str, holder_id: str, connector_id: str) -> str:
    return f"mycelic/cred/v1|{tenant_id}|{holder_id}|{connector_id}"


class TokenVault:
    """master keys -> per-tenant KEKs (HKDF-SHA256) -> per-connector DEK -> credential JSON."""

    def __init__(self, masters: Mapping[str, bytes], active_kid: str) -> None:
        if active_kid not in masters:
            raise VaultUnavailable("active key id is not among the master keys")
        self.masters = dict(masters)
        self.active_kid = active_kid

    @classmethod
    def from_secret(cls, secret: str, previous: list[str] | tuple[str, ...] = ()) -> "TokenVault":
        if not secret:
            raise VaultUnavailable("no master key configured")
        active = secret.encode("utf-8")
        masters = {kid_for(active): active, legacy_kid_for(active): active}
        for p in previous:
            if p:
                b = p.encode("utf-8")
                masters.setdefault(kid_for(b), b)
                masters.setdefault(legacy_kid_for(b), b)
        return cls(masters, kid_for(active))

    @classmethod
    def from_settings(cls, settings: Any, *, environ: Mapping[str, str] | None = None) -> "TokenVault":
        """``MYCELIC_SECRET_KEY`` from the environment is accepted. A key that only exists in ``<data_dir>/secret_key``
        (generated by ``runtime.ensure_secret_key``) is refused unless ``MYCELIC_ALLOW_LOCAL_KEK=1``."""
        env = os.environ if environ is None else environ
        secret = str(getattr(settings, "secret_key", "") or "")
        from_env = str(env.get("MYCELIC_SECRET_KEY") or "")
        if not secret:
            raise VaultUnavailable("no master key configured (MYCELIC_SECRET_KEY)")
        if secret != from_env:
            local = Path(str(getattr(settings, "data_dir", "") or ".")) / "secret_key"
            generated = local.exists() and local.read_text().strip() == secret
            if generated and env.get("MYCELIC_ALLOW_LOCAL_KEK") != "1":
                raise VaultUnavailable("the master key was generated next to the data; set MYCELIC_SECRET_KEY "
                                       "(or MYCELIC_ALLOW_LOCAL_KEK=1 for development)")
        previous = [p.strip() for p in str(env.get("MYCELIC_SECRET_KEY_PREVIOUS") or "").split(",") if p.strip()]
        return cls.from_secret(secret, previous)

    # ------------------------------------------------------------------ keys
    def _kek(self, kid: str, tenant_id: str) -> bytes:
        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.primitives.kdf.hkdf import HKDF
        if kid not in self.masters:
            raise CredentialTampered("unknown key id")
        return HKDF(algorithm=hashes.SHA256(), length=32, salt=b"mycelic/kek/v1",
                    info=b"connector-credentials|" + tenant_id.encode("utf-8")).derive(self.masters[kid])

    @staticmethod
    def _seal(key: bytes, plaintext: bytes, aad: bytes) -> bytes:
        nonce = os.urandom(NONCE_BYTES)
        return FORMAT + nonce + _aesgcm()(key).encrypt(nonce, plaintext, aad)

    @staticmethod
    def _open(key: bytes, blob: bytes, aad: bytes) -> bytes:
        from cryptography.exceptions import InvalidTag
        if not blob or blob[:2] != FORMAT or len(blob) < 2 + NONCE_BYTES + 16:
            raise CredentialTampered("malformed sealed value")
        try:
            return _aesgcm()(key).decrypt(blob[2:2 + NONCE_BYTES], blob[2 + NONCE_BYTES:], aad)
        except InvalidTag:
            raise CredentialTampered("authentication failed") from None

    # ------------------------------------------------------------------ API
    def seal(self, *, tenant_id: str, holder_id: str, connector_id: str, credentials: Credentials) -> SealedCredentials:
        dek = os.urandom(32)
        aad = aad_for(tenant_id, holder_id, connector_id).encode("utf-8")
        wrapped = self._seal(self._kek(self.active_kid, tenant_id), dek, aad + b"|wrap")
        ct = self._seal(dek, json.dumps(credentials.to_storable(), sort_keys=True, separators=(",", ":")).encode("utf-8"), aad)
        return SealedCredentials(kid=self.active_kid, wrapped_dek=wrapped, ciphertext=ct, aad=aad.decode("utf-8"))

    def _unwrap(self, row: SealedCredentials, tenant_id: str, aad: bytes) -> bytes:
        return self._open(self._kek(row.kid, tenant_id), row.wrapped_dek, aad + b"|wrap")

    def open(self, row: SealedCredentials, *, tenant_id: str, holder_id: str, connector_id: str) -> Credentials:
        """Recomputes the AAD from the caller's ids; the stored ``aad`` column is informational only."""
        aad = aad_for(tenant_id, holder_id, connector_id).encode("utf-8")
        dek = self._unwrap(row, tenant_id, aad)
        try:
            data = json.loads(self._open(dek, row.ciphertext, aad).decode("utf-8"))
        except (UnicodeDecodeError, ValueError):
            raise CredentialTampered("credential payload is not valid") from None
        return Credentials.from_storable(data)

    def replace_credentials(self, row: SealedCredentials, *, tenant_id: str, holder_id: str, connector_id: str,
                            credentials: Credentials) -> SealedCredentials:
        """After a token refresh: same DEK, fresh nonce, new ciphertext."""
        aad = aad_for(tenant_id, holder_id, connector_id).encode("utf-8")
        dek = self._unwrap(row, tenant_id, aad)
        ct = self._seal(dek, json.dumps(credentials.to_storable(), sort_keys=True, separators=(",", ":")).encode("utf-8"), aad)
        return SealedCredentials(kid=row.kid, wrapped_dek=row.wrapped_dek, ciphertext=ct, aad=row.aad)

    def rewrap(self, row: SealedCredentials, *, tenant_id: str, holder_id: str, connector_id: str) -> SealedCredentials:
        """Key rotation: unwrap the DEK with the row's key id and wrap it with the active one; the ciphertext is unchanged."""
        aad = aad_for(tenant_id, holder_id, connector_id).encode("utf-8")
        dek = self._unwrap(row, tenant_id, aad)
        wrapped = self._seal(self._kek(self.active_kid, tenant_id), dek, aad + b"|wrap")
        return SealedCredentials(kid=self.active_kid, wrapped_dek=wrapped, ciphertext=row.ciphertext, aad=row.aad)


# ---------------------------------------------------------------------------------------------- credential transfer (§10.1)
# A token entered in the coordinator UI (or obtained by an OAuth flow that terminates at the core API) reaches its holder
# inside a ``connector_control`` envelope. The transport stores envelopes (SQLite outbox, JetStream), so the token
# travels sealed with a key derived from the holder's route key, bound to the holder and to the envelope's msg_id. Only
# the coordinator and that holder know the route key; a copy of the transport's storage alone reveals nothing, and a
# sealed blob replayed into another envelope or to another holder fails authentication. The core never stores the token.
TRANSFER_INFO = b"mycelic/credential-transfer/v1|"


def _transfer_key(route_key: str, holder_id: str) -> bytes:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF
    if not route_key:
        raise VaultUnavailable("no route key for the credential transfer")
    return HKDF(algorithm=hashes.SHA256(), length=32, salt=b"mycelic/transfer/v1",
                info=TRANSFER_INFO + holder_id.encode("utf-8")).derive(route_key.encode("utf-8"))


def seal_transfer(route_key: str, holder_id: str, msg_id: str, data: Mapping[str, Any]) -> str:
    import base64
    blob = TokenVault._seal(_transfer_key(route_key, holder_id), json.dumps(dict(data), sort_keys=True, separators=(",", ":")).encode("utf-8"),
                            f"{holder_id}|{msg_id}".encode("utf-8"))
    return base64.urlsafe_b64encode(blob).decode("ascii")


def open_transfer(route_key: str, holder_id: str, msg_id: str, sealed: str) -> dict[str, Any]:
    import base64
    import binascii
    try:
        blob = base64.urlsafe_b64decode(sealed.encode("ascii"))
    except (binascii.Error, ValueError, UnicodeEncodeError):
        raise CredentialTampered("malformed credential transfer") from None
    raw = TokenVault._open(_transfer_key(route_key, holder_id), blob, f"{holder_id}|{msg_id}".encode("utf-8"))
    try:
        out = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError):
        raise CredentialTampered("credential transfer payload is not valid") from None
    if not isinstance(out, dict):
        raise CredentialTampered("credential transfer payload is not an object")
    return out
