#!/usr/bin/env python3
"""Builds the canonical application ledger.

Every row below came from a live WebSearch result in this session. No posting was
invented. Because WebFetch is blocked for all domains in this environment, NO job
page could be opened -- so date_posted and remote_status are marked UNVERIFIED
unless the search snippet itself stated them. Nothing here is marked "Applied",
because no application was or could be submitted.
"""
import csv, json

FIELDS = ["company","role","job_url","location","remote_status","date_posted",
          "salary","fit_score","status","application_datetime","resume_version",
          "reason_skipped_blocked","notes","confirmation_number"]

# fit sub-scores: (tech30, evidence25, airel20, upside10, comp10, friction5)
def s(*p): return sum(p)

ROWS = [
 dict(company="Arize AI", role="AI Product Engineer, New Grad",
   job_url="https://job-boards.greenhouse.io/arizeai/jobs/5396470004",
   location="Remote-first (NYC + SF Bay offices)", remote_status="Remote-first per search snippet (UNVERIFIED on page)",
   date_posted="UNVERIFIED", salary="$100,000-$135,000 + equity (per snippet)",
   fit_score=s(27,24,19,9,8,4), status="Needs Verification", application_datetime="",
   resume_version="v1-eval", reason_skipped_blocked="",
   notes="HIGHEST FIT. Arize builds LLM observability/evaluation tooling (Phoenix). Ali's two Mercor eval roles + rubric/benchmark design map directly onto the product domain. 'New Grad' title needs grad-window check against May 2027."),
 dict(company="Scale AI", role="Software Engineer - New Grad",
   job_url="https://job-boards.greenhouse.io/scaleai/jobs/4730836005",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(24,22,17,9,9,4), status="Needs Verification", application_datetime="",
   resume_version="v1-eval", reason_skipped_blocked="",
   notes="Search snippet states requirement: 'graduation date in Fall 2026 or Spring 2027'. May 2027 = Spring 2027 -> ELIGIBLE. Scale's core business is exactly the eval/post-training data work Ali does at Mercor."),
 dict(company="OpenAI", role="Residency (6-month, pathway to full-time)",
   job_url="https://openai.com/residency/",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="Program page, not a dated req", salary="UNVERIFIED",
   fit_score=s(26,22,20,10,9,3), status="Needs Verification", application_datetime="",
   resume_version="v1-eval", reason_skipped_blocked="",
   notes="Explicitly targets people from math/physics adjacent backgrounds moving into AI. Ali's adversarial-math-for-LLM-reasoning work at Mercor is an unusually on-point match. Also check OpenAI 'Emerging Talent' (0-3 yrs experience) per snippet."),
 dict(company="Cohere", role="Applied AI Engineer, Agents & Automations",
   job_url="https://jobs.ashbyhq.com/cohere/3fe03041-347a-479f-8361-6b1f5f81338e",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(25,22,19,9,9,4), status="Needs Verification", application_datetime="",
   resume_version="v1-agents", reason_skipped_blocked="",
   notes="Agents + automations is Ali's Mycelic/Fujitsu-agent lane. Likely asks for more YoE than resume shows - per instructions, do not auto-reject; lead with the provisional patent and the Fujitsu agent that cut troubleshooting 48h->20min."),
 dict(company="Neuromorphic Labs", role="Founding Forward Deployed AI Engineer",
   job_url="https://jobs.ashbyhq.com/Neuromorphic-Labs/78dd02e0-c0bf-4c4a-8d48-f5bab85c290c",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(22,18,17,9,6,4), status="Needs Verification", application_datetime="",
   resume_version="v1-agents", reason_skipped_blocked="",
   notes="Seed-stage; deploying platform into production AI environments. Fujitsu enablement work (live demos, prompt libraries, driving adoption across teams) is genuine forward-deployed evidence."),
 dict(company="Clera", role="Founding AI Engineer",
   job_url="https://jobs.ashbyhq.com/clera/3a7488e5-b7df-45fd-acc9-a4796dcbe7a8",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(21,17,15,9,6,4), status="Needs Verification", application_datetime="",
   resume_version="v1-agents", reason_skipped_blocked="",
   notes="Early-stage consumer social AI. Founding role = high upside, low comp certainty. Weaker domain overlap than Arize/Scale but strong build-from-scratch signal in Mycelic."),
 dict(company="Twilio", role="Machine Learning Engineer",
   job_url="https://job-boards.greenhouse.io/twilio/jobs/7702644",
   location="Remote US", remote_status="Remote, NOT eligible in CA, CT, NJ, NY, PA, WA (per snippet). TX is eligible.",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(20,16,14,7,8,4), status="Needs Verification", application_datetime="",
   resume_version="v1-swe", reason_skipped_blocked="",
   notes="Remote-US and Katy TX is in an eligible state. Likely a mid-level req; apply only if the YoE ask is within reach."),
 dict(company="Workiva", role="Summer 2027 Intern - Machine Learning Engineering",
   job_url="https://workiva.wd503.myworkdayjobs.com/careers/job/USA---Remote/Summer-2027-Intern---Machine-Learning-Engineering_R12194-1",
   location="USA - Remote", remote_status="Remote US (in the job URL path)",
   date_posted="UNVERIFIED (a snippet claimed 'within the last week' - unconfirmed)", salary="UNVERIFIED",
   fit_score=s(19,15,15,7,7,4), status="Needs Input", application_datetime="",
   resume_version="v1-eval", reason_skipped_blocked="Grad-window eligibility unknown; Workday requires account creation + email verification",
   notes="Genuinely remote-US ML internship. MUST check grad-date window: many Summer 2027 programs require graduation Dec 2027 or later, which would exclude a May 2027 grad."),
 dict(company="Experian", role="ML Engineer Summer Intern (Remote & Paid)",
   job_url="https://jobs.experian.com/job/ml-engineer-summer-intern-remote-and-paid-in-united-states-jid-3340",
   location="United States", remote_status="Remote (stated in title)",
   date_posted="UNVERIFIED", salary="Paid (amount UNVERIFIED)",
   fit_score=s(19,15,15,7,7,4), status="Needs Input", application_datetime="",
   resume_version="v1-eval", reason_skipped_blocked="Grad-window eligibility unknown",
   notes="Works under VP of Innovation Engineering on ML + generative AI. Remote and explicitly paid. Same grad-window caveat as Workiva."),
 dict(company="HOPPR", role="Machine Learning Engineer",
   job_url="https://job-boards.greenhouse.io/hoppr/jobs/4830483008",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(18,14,15,7,7,4), status="Needs Verification", application_datetime="",
   resume_version="v1-swe", reason_skipped_blocked="",
   notes="Medical-imaging foundation models. Domain overlap is thin; no medical ML on resume. Borderline - verify seniority before spending an application."),
 dict(company="Bjak", role="Founding AI Software Engineer (Remote)",
   job_url="https://jobs.ashbyhq.com/bjakcareer/4eb18042-9a3a-4911-9ff5-0f4797fbb2a6",
   location="UNVERIFIED (Bjak is Malaysia-headquartered)", remote_status="Remote - US eligibility UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(20,16,15,7,5,3), status="Needs Verification", application_datetime="",
   resume_version="v1-agents", reason_skipped_blocked="",
   notes="Verify that US-based applicants are eligible before applying - the mission requires US eligibility and this is an APAC company."),
 dict(company="Samsung Research America", role="Internship (2 reqs, titles unread)",
   job_url="https://job-boards.greenhouse.io/samsungresearchamericainternship/jobs/8375384002",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=0, status="Needs Verification", application_datetime="",
   resume_version="", reason_skipped_blocked="Could not read page title or body - egress blocked",
   notes="Second req: https://job-boards.greenhouse.io/samsungresearchamericainternship/jobs/8332828002 . Cannot score without reading the postings."),
 dict(company="C3 AI", role="Ascend Internship Program: Summer 2027",
   job_url="https://job-boards.greenhouse.io/c3ascend",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="Board index, not a single req", salary="UNVERIFIED",
   fit_score=0, status="Needs Verification", application_datetime="",
   resume_version="", reason_skipped_blocked="Board index URL, not an individual requisition",
   notes="Enterprise AI applications. Open the board and score individual reqs; same May-2027 grad-window question applies."),
 dict(company="Anduril Industries", role="2027 Software Engineer Intern",
   job_url="https://job-boards.greenhouse.io/andurilindustries/jobs/5148079007?gh_jid=5148079007",
   location="UNVERIFIED", remote_status="UNVERIFIED (defense work is typically onsite)",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(17,12,10,8,8,3), status="Needs Input", application_datetime="",
   resume_version="v1-swe", reason_skipped_blocked="BLOCKING: US defense roles routinely require citizenship and/or clearance eligibility. Resume states neither. Per instructions I must not answer clearance or citizenship questions.",
   notes="Do not submit until Ali supplies citizenship/clearance answers. Low AI relevance for his lane anyway."),
 dict(company="PDT Partners", role="Summer 2027 Software Engineering Intern",
   job_url="https://job-boards.greenhouse.io/pdtpartners/jobs/8077685",
   location="UNVERIFIED (PDT is NYC-based)", remote_status="UNVERIFIED - quant funds are near-universally onsite",
   date_posted="UNVERIFIED", salary="UNVERIFIED (quant internships pay very well)",
   fit_score=s(16,10,8,8,10,3), status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="Fails the remote requirement in all likelihood, and AI/ML relevance is low for Ali's stated targeting priorities.",
   notes="Kept in ledger for auditability. Revisit only if Ali drops the remote constraint."),
 dict(company="Google", role="Software Engineering Intern, BS, Summer 2027",
   job_url="https://www.google.com/about/careers/applications/jobs/results/100648618540573382-software-engineering-intern-bs-summer-2027",
   location="UNVERIFIED", remote_status="Google SWE internships are onsite/hybrid",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=0, status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="INELIGIBLE: search result states Google requires applicants to be in their penultimate academic year or returning to a degree program after the internship. A May 2027 graduate is in their FINAL year in 2026-27 and does not return.",
   notes="Apply instead to Google's 2027 new-grad SWE reqs when they open."),
 dict(company="Intuit", role="Summer 2027 Software Engineering Intern - Full Stack",
   job_url="https://jobs.intuit.com/job/mountain-view/summer-2027-software-engineering-intern-full-stack/27595/99856180864",
   location="Mountain View, CA", remote_status="Onsite",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=0, status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="INELIGIBLE + not remote: Intuit requires an expected graduation date AFTER the internship ends. Cohorts end Aug 6 / Sep 3 2027; Ali graduates May 2027.",
   notes="This is the clearest documented example of the grad-window rule that disqualifies Ali from most Summer 2027 internships."),
 dict(company="Rula", role="Sr. Staff AI Engineer - Applied AI (Remote)",
   job_url="https://jobs.ashbyhq.com/rula/f2424794-c819-4f53-a8af-83322e617acb",
   location="Remote", remote_status="Remote",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(12,6,15,5,8,4), status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="Sr. Staff level. The gap between an undergraduate with ~1.25 yrs of dated AI work and a Sr. Staff req is not a 'somewhat more experience' gap - it is several levels. Applying would be a bad-faith use of the recruiter's time.",
   notes="Rula does have an applied-AI function though - worth watching for a junior/mid req on the same board."),
 dict(company="NewsBreak", role="Machine Learning Engineer (Junior & New Grad)",
   job_url="https://job-boards.greenhouse.io/newsbreak/jobs/4338876006",
   location="Bellevue, WA and Mountain View, CA", remote_status="NOT remote (two named offices, per snippet)",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=s(20,15,14,7,7,4), status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="Fails the remote-eligible requirement: posting lists two specific US offices and no remote option.",
   notes="Seniority ('Junior & New Grad') is otherwise a good match. Revisit if Ali will consider relocation - that is his call to make, not mine."),
 dict(company="Handshake AI", role="AI Fellowship (model evaluation)",
   job_url="https://joinhandshake.com/ai/opportunities/",
   location="Remote", remote_status="Remote, part-time",
   date_posted="Rolling program", salary="Up to $100/hr (per snippet)",
   fit_score=s(24,20,18,6,7,5), status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="Stated eligibility is PhD & Masters holders. Ali is an undergraduate - claiming eligibility would be fabricating a credential.",
   notes="Work content is a near-perfect match for his Mercor experience. Worth an email asking whether undergraduates with frontier-eval experience are considered - that is a legitimate ask, unlike a false application."),
 dict(company="TechNovaTime (Techstars)", role="Founding Engineer",
   job_url="https://jobs.techstars.com/companies/technovatime/jobs/73782177-founding-engineer",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="Posted April 9, 2026 (per snippet)", salary="UNVERIFIED",
   fit_score=0, status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="Fails the <=7-day freshness filter: posted 2026-04-09, roughly 5 months old.",
   notes="AI orchestration + computer-use workflows for healthcare; content would otherwise fit the agent-infrastructure lane."),
 dict(company="hapiy.ai (via Built In)", role="Founding Software Engineer",
   job_url="https://builtin.com/job/founding-software-engineer/7188513",
   location="Remote Boston", remote_status="Remote",
   date_posted="~3 months ago (per snippet)", salary="UNVERIFIED",
   fit_score=0, status="Skipped", application_datetime="",
   resume_version="", reason_skipped_blocked="Fails the <=7-day freshness filter (~3 months old per search snippet).",
   notes="'Trust layer for enterprise AI'. Check whether a fresher req exists on their own site."),
 dict(company="Unnamed (via Built In)", role="Machine Learning Engineer",
   job_url="https://builtin.com/job/machine-learning-engineer/4742093",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=0, status="Needs Verification", application_datetime="",
   resume_version="", reason_skipped_blocked="Aggregator listing; company and details unreadable without opening the page.",
   notes="Built In is an aggregator - prefer finding this req on the company's own ATS to satisfy the 'prefer official application page' rule."),
 dict(company="Unnamed (via Built In)", role="Founding Engineer",
   job_url="https://builtin.com/job/founding-engineer/4480044",
   location="UNVERIFIED", remote_status="UNVERIFIED",
   date_posted="UNVERIFIED", salary="UNVERIFIED",
   fit_score=0, status="Needs Verification", application_datetime="",
   resume_version="", reason_skipped_blocked="Aggregator listing; company and details unreadable without opening the page.",
   notes="Same as above - resolve to the underlying ATS req before evaluating."),
]

with open("/home/user/NeuralGraph/jobsearch/ledger.csv","w",newline="") as f:
    w = csv.DictWriter(f, fieldnames=FIELDS)
    w.writeheader()
    for r in ROWS:
        w.writerow({k: r.get(k,"") for k in FIELDS})

from collections import Counter
c = Counter(r["status"] for r in ROWS)
print("rows:", len(ROWS))
for k,v in sorted(c.items()): print(f"  {k}: {v}")
scored = [r for r in ROWS if r["fit_score"]]
print("scored:", len(scored), "| >=65:", sum(1 for r in scored if r["fit_score"]>=65))
print("\ntop by fit:")
for r in sorted(scored, key=lambda r:-r["fit_score"])[:8]:
    print(f'  {r["fit_score"]:3d}  {r["company"]} — {r["role"]}')
