"""Emit every manuscript table from the pinned coordination artifacts.

The manuscript must never contain a hand-typed number. Each table below is
generated from a file in ``NeuralGraph/coordination/artifacts/``, whose digests
are pinned in ``SHA256SUMS`` and regenerated byte-for-byte by
``test_artifact_reproducibility.py``. If a table in the paper disagrees with
this script's output, the paper is wrong.

    python3.11 -m tools.build_paper_tables --check
    python3.11 -m tools.build_paper_tables --output docs/paper/tables.md

``--check`` verifies the artifact digests against SHA256SUMS before emitting
anything, so a table can never be built from an artifact that drifted.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ARTIFACTS = Path("NeuralGraph/coordination/artifacts")

SWEEP = "benchmark_sweep30_seed20260813.json"
SCALE = "scale_seed20260813.json"
EXPERIMENT = "experiment_seed20260813.json"


def load(name: str) -> dict:
    return json.loads((ARTIFACTS / name).read_text(encoding="utf-8"))


def verify_digests() -> list[str]:
    """Return a list of mismatches against the pinned SHA256SUMS."""
    problems: list[str] = []
    for line in (ARTIFACTS / "SHA256SUMS").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        expected, _, name = line.partition("  ")
        name = name.strip()
        path = ARTIFACTS / name
        if not path.exists():
            problems.append(f"missing artifact: {name}")
            continue
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != expected:
            problems.append(f"digest drift: {name}\n  pinned {expected}\n  actual {actual}")
    return problems


def table_survival() -> str:
    """Table 1: the 8 x 9 headline. Survival and silent forgetting over 30 seeds."""
    d = load(SWEEP)
    order = [
        "isolated_local", "centralized", "fixed_distributed_replication",
        "source_count_repair", "full_replication", "random_path_diversification",
        "lineage_aware_repair", "oracle_min_cut",
    ]
    rows = [
        "| strategy | capability survival | unrecovered silent forgetting | mean bytes moved |",
        "|---|---|---|---|",
    ]
    for s in order:
        v = d["per_strategy"][s]
        rows.append(
            f"| `{s}` | {v['capability_survival_rate']:.3f} | "
            f"{v['unrecovered_silent_forgetting_rate']:.3f} | "
            f"{v['mean_bytes_moved']:,.0f} |"
        )
    head = (
        f"Mean over {len(d['seeds'])} seeds, "
        f"{len(d['strategies'])} strategies x {len(d['interventions'])} interventions "
        f"= {len(d['cells'])} cells.\n\n"
    )
    return head + "\n".join(rows)


def table_matrix() -> str:
    """Table 2: the full strategy x intervention survival matrix."""
    d = load(SWEEP)
    ivs = d["interventions"]
    short = {iv: iv.replace("_failure", "").replace("_", " ")[:12] for iv in ivs}
    rows = ["| strategy | " + " | ".join(short[i] for i in ivs) + " |",
            "|---" * (len(ivs) + 1) + "|"]
    for s in d["strategies"]:
        cells = []
        for iv in ivs:
            c = d["cells"][f"{s}::{iv}"]
            cells.append(f"{c['survival_rate']:.2f}")
        rows.append(f"| `{s}` | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def table_independence() -> str:
    """Table 3: survival by lineage independence, and scale invariance.

    This is the table that shows independence -- not K, not H -- is the
    load-bearing variable, and the one cell where lineage_aware loses.
    """
    d = load(SCALE)
    rows = [
        "| repair policy | intervention | independent roots | survival | invariant across scale |",
        "|---|---|---|---|---|",
    ]
    for key, v in sorted(d["survival_by_independence"].items()):
        policy, intervention, ind = key.split("::")
        rows.append(
            f"| `{policy}` | {intervention} | {ind[1:]} | "
            f"{v['survival_rate']:.2f} | {'yes' if v['invariant_across_scale'] else 'NO'} |"
        )
    note = (
        f"\n\nSpecs: {', '.join(d['specs'])} "
        f"(K = holders per slot, H = slots, I = independent roots).\n"
    )
    return "\n".join(rows) + note


def table_cost_by_arity() -> str:
    """Table 4: cost scaling with capability arity."""
    d = load(SCALE)
    rows = ["| arity | mean records | mean route size | mean bytes moved | all baselines correct |",
            "|---|---|---|---|---|"]
    for k, v in sorted(d["cost_by_arity"].items(), key=lambda kv: int(kv[0][1:])):
        rows.append(
            f"| {k[1:]} | {v['mean_record_count']:.1f} | {v['mean_route_size']:.1f} | "
            f"{v['mean_bytes_moved']:,.0f} | {'yes' if v['all_baselines_correct'] else 'NO'} |"
        )
    return "\n".join(rows)


def table_replication_effect() -> str:
    """Table 5: replication under correlated lineage. Every cell is zero."""
    d = load(SCALE)
    rows = ["| policy | slots | independent roots | survival |", "|---|---|---|---|"]
    for key, rate in sorted(d["replication_effect_under_correlated_lineage"].items()):
        policy, h, i = key.split("::")
        rows.append(f"| `{policy}` | {h[1:]} | {i[1:]} | {rate:.2f} |")
    return "\n".join(rows)


def counter_results() -> str:
    """The results reported against interest, straight from the artifact."""
    d = load(SWEEP)
    out = []

    part = [(s, d["cells"][f"{s}::network_partition"]["survival_rate"])
            for s in d["strategies"]]
    survive = [s for s, r in part if r > 0]
    out.append(
        "**N1 - distribution loses to centralization under partition.** "
        f"Survivors: {', '.join('`' + s + '`' for s in survive)}. "
        f"All {len(part) - len(survive)} other strategies score 0.00, including "
        "every distributed one. Keeping every premise on one node is what "
        "survives a partition; that is the real cost of distribution."
    )

    dd = load(SCALE)
    losing = [
        k for k, v in dd["survival_by_independence"].items()
        if k.startswith("lineage_aware::")
        and v["survival_rate"] == 0.0
        and dd["survival_by_independence"][k.replace("lineage_aware", "source_count")]["survival_rate"] == 1.0
    ]
    out.append(
        "**N2 - lineage-aware repair does not dominate.** It loses to "
        f"`source_count` in exactly {len(losing)} of "
        f"{len(dd['survival_by_independence']) // 2} cells: "
        f"{', '.join('`' + k + '`' for k in losing)}. With a single independent "
        "root there is no independent holder to find, so refusing every "
        "correlated holder discards a replica that would have served."
    )

    worst = [(s, d["cells"][f"{s}::worst_single_domain_failure"]["survival_rate"])
             for s in d["strategies"]]
    won = [s for s, r in worst if r > 0]
    out.append(
        "**C5 - min-cut predicts survival.** Under `worst_single_domain_failure`, "
        f"which fails exactly one domain and never a whole cut, only "
        f"{', '.join('`' + s + '`' for s in won)} survives -- the only "
        "placement with a minimum failure-domain cut of 2."
    )
    return "\n\n".join(out)


SECTIONS = [
    ("Table 1 - Headline: capability survival and silent forgetting", table_survival),
    ("Table 2 - Full survival matrix (strategy x intervention)", table_matrix),
    ("Table 3 - Survival by lineage independence and scale", table_independence),
    ("Table 4 - Cost by capability arity", table_cost_by_arity),
    ("Table 5 - Replication under correlated lineage", table_replication_effect),
    ("Results reported against interest", counter_results),
]


def build() -> str:
    parts = [
        "<!-- GENERATED by tools/build_paper_tables.py. Do not edit by hand. -->",
        "# Manuscript tables",
        "",
        "Every number below is read from a pinned artifact in "
        "`NeuralGraph/coordination/artifacts/`. Regenerate with:",
        "",
        "```",
        "python3.11 -m tools.build_paper_tables --output docs/paper/tables.md",
        "```",
        "",
    ]
    for title, fn in SECTIONS:
        parts.append(f"## {title}\n")
        parts.append(fn())
        parts.append("")
    return "\n".join(parts) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--output", type=Path)
    ap.add_argument("--check", action="store_true",
                    help="verify artifact digests against SHA256SUMS and exit")
    args = ap.parse_args(argv)

    problems = verify_digests()
    if problems:
        for p in problems:
            print(f"ARTIFACT PROBLEM: {p}", file=sys.stderr)
        return 1
    if args.check:
        print("all pinned artifact digests match")
        return 0

    text = build()
    if args.output:
        args.output.write_text(text, encoding="utf-8")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
