"""Generate CODEMAP.md: every source file, its symbols, and their line numbers.

The map exists so a session can jump straight to ``file:line`` instead of
reading whole modules to find one function.  It is generated, never
hand-edited, and a test asserts it is current::

    python -m tools.codemap            # rewrite CODEMAP.md
    python -m tools.codemap --check    # exit 1 if CODEMAP.md is stale

Python files are parsed with ``ast`` (classes, methods, functions, async
functions, ALL_CAPS module constants).  Markdown files contribute their
headings.  Pinned JSON artifacts contribute size only.  Nothing here imports
project code, so the map can be built from a clean checkout with no
dependencies installed.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "CODEMAP.md"

INCLUDE_DIRS = ("NeuralGraph", "evaluation", "tools", "demo", "docs")
EXCLUDE_PARTS = {"__pycache__", ".git", ".pytest_cache", "archive", "results", "emb_cache"}
ROOT_DOCS = ("CLAUDE.md", "state.md", "README.md", "AUDIT.md", "VERIFICATION.md", "CLEANUP_PLAN.md", "info.md")
MAX_JSON_BYTES_SHOWN = 10  # json files list size only


def _wanted(path: Path) -> bool:
    if any(part in EXCLUDE_PARTS for part in path.parts):
        return False
    return path.suffix in {".py", ".md", ".json", ".ini", ".txt"}


def iter_files() -> list[Path]:
    files: list[Path] = []
    for name in ROOT_DOCS + ("requirements.txt", "pytest.ini", ".gitignore"):
        candidate = ROOT / name
        if candidate.is_file():
            files.append(candidate)
    for directory in INCLUDE_DIRS:
        base = ROOT / directory
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_file() and _wanted(path):
                files.append(path)
    return files


def _first_doc_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node, clean=True)
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


def python_entries(path: Path) -> tuple[str, list[str]]:
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:  # pragma: no cover - a broken file is still mapped
        return "", [f"  (syntax error: line {exc.lineno})"]
    lines: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bases = ", ".join(ast.unparse(base) for base in node.bases)
            suffix = f"({bases})" if bases else ""
            lines.append(f"  L{node.lineno:<5} class {node.name}{suffix}")
            for child in node.body:
                if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    kind = "async def" if isinstance(child, ast.AsyncFunctionDef) else "def"
                    lines.append(f"  L{child.lineno:<5}   {kind} {child.name}")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            kind = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
            lines.append(f"  L{node.lineno:<5} {kind} {node.name}")
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            names = [t.id for t in targets if isinstance(t, ast.Name) and t.id.isupper()]
            if names:
                lines.append(f"  L{node.lineno:<5} {' = '.join(names)} = …")
    return _first_doc_line(tree), lines


def markdown_entries(path: Path) -> list[str]:
    lines: list[str] = []
    in_code = False
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if raw.startswith("```"):
            in_code = not in_code
            continue
        if in_code or not raw.startswith("#"):
            continue
        level = len(raw) - len(raw.lstrip("#"))
        if level > 3:
            continue
        title = raw[level:].strip()
        lines.append(f"  L{number:<5} {'#' * level} {title}")
    return lines


def render() -> str:
    out: list[str] = [
        "# Code map",
        "",
        "Generated by `python -m tools.codemap`; checked by `tests/test_codemap.py`.",
        "Jump to `file:line` instead of reading a module to find a symbol.",
        "Do not hand-edit. Regenerate after adding or moving a definition.",
        "",
    ]
    current_dir = None
    for path in iter_files():
        rel = path.relative_to(ROOT).as_posix()
        top = rel.split("/", 1)[0] if "/" in rel else "."
        if top != current_dir:
            current_dir = top
            out.append(f"## {top}")
            out.append("")
        text = path.read_text(encoding="utf-8", errors="replace")
        line_count = text.count("\n") + (0 if text.endswith("\n") or not text else 1)
        if path.suffix == ".py":
            doc, entries = python_entries(path)
            head = f"### `{rel}` ({line_count} lines)"
            out.append(head)
            if doc:
                out.append(f"{doc}")
            out.append("")
            out.append("```")
            out.extend(entries or ["  (no top-level definitions)"])
            out.append("```")
        elif path.suffix == ".md":
            entries = markdown_entries(path)
            out.append(f"### `{rel}` ({line_count} lines)")
            out.append("")
            out.append("```")
            out.extend(entries or ["  (no headings)"])
            out.append("```")
        else:
            size = path.stat().st_size
            out.append(f"### `{rel}` ({line_count} lines, {size} bytes)")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if CODEMAP.md is stale")
    args = parser.parse_args(argv)
    content = render()
    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != content:
            sys.stderr.write("CODEMAP.md is stale; run: python -m tools.codemap\n")
            return 1
        print("CODEMAP.md is current")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
